services:
    backend:
        name: Mario Kart Tournament
        description: Python app running on port 5000
        commands:
            start: python3 main.py
        triggeredBy:
            - manual
