services:
    backend:
        name: Backend Service
        description: Example service simulating a backend
        commands:
            start: python3 main.py
        triggeredBy:
            - manual
